"""The company Disciplinary Action Policy, from "Disciplinary Action Policy.xlsx" (2026-10-02): the
penalty for a first / second / third offence and the rewards. Loaded by `manage.py load_disciplinary_policy`.

A money amount is filled in only where the penalty is plainly a fixed sum; penalties that are warnings,
suspensions, dismissal or depend on a cost, a salary or a team have no amount and are decided case by case."""

POLICY_NOTE = ('Note: Suspension is unpaid and observed outside of the company premises. You must leave the hostel during '
 'your suspension. Any other offence not stated above are at the discretion of the disciplinary committee')

OFFENCES = [{'category': 'Safety',
  'name': 'Entering factory without safety boots',
  'sort_order': 1,
  'penalty_first': 'Send back with verbal warning',
  'penalty_second': 'Confiscation of footwear + N5,000',
  'penalty_third': 'Dismissal',
  'amount_first': None,
  'amount_second': 5000,
  'amount_third': None},
 {'category': 'Safety',
  'name': 'Misplacing hand gloves before the expected period of use.',
  'sort_order': 2,
  'penalty_first': '₦500',
  'penalty_second': 'Full cost of a new pair of handglove',
  'penalty_third': 'Full cost of a new pair of handglove',
  'amount_first': 500,
  'amount_second': None,
  'amount_third': None},
 {'category': 'Safety',
  'name': 'Misplacing ear plugs',
  'sort_order': 3,
  'penalty_first': '₦300',
  'penalty_second': '₦300',
  'penalty_third': '₦500',
  'amount_first': 300,
  'amount_second': 300,
  'amount_third': 500},
 {'category': 'Safety',
  'name': 'Working without PPE',
  'sort_order': 4,
  'penalty_first': '₦1,000',
  'penalty_second': '₦2,000',
  'penalty_third': 'Query & 3 days suspension',
  'amount_first': 1000,
  'amount_second': 2000,
  'amount_third': None},
 {'category': 'Safety',
  'name': 'Unsafe behaviour',
  'sort_order': 5,
  'penalty_first': 'verbal warning & 5,000',
  'penalty_second': 'query, 1 week suspension & final warning',
  'penalty_third': 'Dismissal from duty',
  'amount_first': 5000,
  'amount_second': None,
  'amount_third': None},
 {'category': 'Safety',
  'name': 'Covering up incidents or accidents',
  'sort_order': 6,
  'penalty_first': '₦3,000',
  'penalty_second': '₦5,000',
  'penalty_third': '1 week suspension',
  'amount_first': 3000,
  'amount_second': 5000,
  'amount_third': None},
 {'category': 'Safety',
  'name': 'Allowing unsafe or unqualified persons to operate machines',
  'sort_order': 7,
  'penalty_first': 'Query, 1st warning',
  'penalty_second': '2nd query, final warning & 3 days working suspension',
  'penalty_third': '1 week suspension or dismissal',
  'amount_first': None,
  'amount_second': None,
  'amount_third': None},
 {'category': 'Safety',
  'name': 'Unauthorised change of machines setting (Switching on, off, or change over)',
  'sort_order': 8,
  'penalty_first': '₦10,000',
  'penalty_second': '50% of salary',
  'penalty_third': 'Dismissal from duty',
  'amount_first': 10000,
  'amount_second': None,
  'amount_third': None},
 {'category': 'Safety',
  'name': 'Unauthorized use of equipment (e.g. computers, forklifts, tools for personal work)',
  'sort_order': 9,
  'penalty_first': '₦20,000',
  'penalty_second': 'Suspension',
  'penalty_third': 'Dismissal from duty',
  'amount_first': 20000,
  'amount_second': None,
  'amount_third': None},
 {'category': 'Attendance',
  'name': 'Late arrival to work after 6:45',
  'sort_order': 10,
  'penalty_first': '₦300',
  'penalty_second': '₦300',
  'penalty_third': '₦500',
  'amount_first': 300,
  'amount_second': 300,
  'amount_third': 500},
 {'category': 'Attendance',
  'name': 'Late arrival to work after 7:00',
  'sort_order': 11,
  'penalty_first': '₦500',
  'penalty_second': '₦800',
  'penalty_third': '₦1,000',
  'amount_first': 500,
  'amount_second': 800,
  'amount_third': 1000},
 {'category': 'Attendance',
  'name': '3 days absence in a month without permission or leave',
  'sort_order': 12,
  'penalty_first': 'Salary deduction according to the number of absent days',
  'penalty_second': 'Eviction from the hostel final warning',
  'penalty_third': 'Dismissal from duty',
  'amount_first': None,
  'amount_second': None,
  'amount_third': None},
 {'category': 'Attendance',
  'name': 'Leaving during work hours without gate pass',
  'sort_order': 13,
  'penalty_first': 'Full day salary',
  'penalty_second': '2 days salary',
  'penalty_third': '3 days suspension',
  'amount_first': None,
  'amount_second': None,
  'amount_third': None},
 {'category': 'Attendance',
  'name': 'Leaving after break without approval',
  'sort_order': 14,
  'penalty_first': 'Full day salary',
  'penalty_second': '2 days salary',
  'penalty_third': '3 days salary',
  'amount_first': None,
  'amount_second': None,
  'amount_third': None},
 {'category': 'Attendance',
  'name': 'Returning from break late',
  'sort_order': 15,
  'penalty_first': '₦300',
  'penalty_second': 'Forfeit meal ticket',
  'penalty_third': 'Paid half day',
  'amount_first': 300,
  'amount_second': None,
  'amount_third': None},
 {'category': 'Attendance',
  'name': 'Signing attendance without being present at work',
  'sort_order': 16,
  'penalty_first': 'Full day salary',
  'penalty_second': 'Full day salary with final warning',
  'penalty_third': 'Suspension',
  'amount_first': None,
  'amount_second': None,
  'amount_third': None},
 {'category': 'Behaviour At Work',
  'name': 'Use of phone during work hours',
  'sort_order': 17,
  'penalty_first': 'Warning',
  'penalty_second': 'Query, written warning & 30,000',
  'penalty_third': 'suspension',
  'amount_first': None,
  'amount_second': 30000,
  'amount_third': None},
 {'category': 'Behaviour At Work',
  'name': 'Loitering within the factory or deliberate delay at the toilet',
  'sort_order': 18,
  'penalty_first': 'Warning',
  'penalty_second': '₦3,000',
  'penalty_third': '₦5,000',
  'amount_first': None,
  'amount_second': 3000,
  'amount_third': 5000},
 {'category': 'Behaviour At Work',
  'name': 'Lack of concentration at work',
  'sort_order': 19,
  'penalty_first': 'Counseling',
  'penalty_second': '₦300',
  'penalty_third': '1 day salary',
  'amount_first': None,
  'amount_second': 300,
  'amount_third': None},
 {'category': 'Behaviour At Work',
  'name': 'Sleeping at work',
  'sort_order': 20,
  'penalty_first': 'Verbal Warning',
  'penalty_second': '₦5,000',
  'penalty_third': '1 day salary',
  'amount_first': None,
  'amount_second': 5000,
  'amount_third': None},
 {'category': 'Behaviour At Work',
  'name': 'Leaving work station to another work station unauthorised',
  'sort_order': 21,
  'penalty_first': 'Verbal Warning',
  'penalty_second': '₦1,000',
  'penalty_third': '1 day salary',
  'amount_first': None,
  'amount_second': 1000,
  'amount_third': None},
 {'category': 'Behaviour At Work',
  'name': 'Leaving work station for entertainment unauthorised',
  'sort_order': 22,
  'penalty_first': '₦5,000',
  'penalty_second': '3 days working suspension',
  'penalty_third': '1 week working suspension',
  'amount_first': 5000,
  'amount_second': None,
  'amount_third': None},
 {'category': 'Behaviour At Work',
  'name': 'Using wrong entry or exit points',
  'sort_order': 23,
  'penalty_first': 'Verbal Warning',
  'penalty_second': '₦500',
  'penalty_third': '₦2,000',
  'amount_first': None,
  'amount_second': 500,
  'amount_third': 2000},
 {'category': 'Behaviour At Work',
  'name': 'Throwing dirt everywhere',
  'sort_order': 24,
  'penalty_first': '₦500',
  'penalty_second': '₦1,000',
  'penalty_third': '₦5,000',
  'amount_first': 500,
  'amount_second': 1000,
  'amount_third': 5000},
 {'category': 'Behaviour At Work',
  'name': 'Switching on the water tank',
  'sort_order': 25,
  'penalty_first': '₦5,000',
  'penalty_second': '₦10,000',
  'penalty_third': '1 week salary',
  'amount_first': 5000,
  'amount_second': 10000,
  'amount_third': None},
 {'category': 'Behaviour At Work',
  'name': 'Resisting being searched by security',
  'sort_order': 26,
  'penalty_first': 'query & warning',
  'penalty_second': '₦5,000',
  'penalty_third': '₦7,000',
  'amount_first': None,
  'amount_second': 5000,
  'amount_third': 7000},
 {'category': 'Behaviour At Work',
  'name': "Sabotage: Deliberate destruction of company's property",
  'sort_order': 27,
  'penalty_first': 'Replacement of damaged property',
  'penalty_second': 'Dismissal & legal action',
  'penalty_third': '',
  'amount_first': None,
  'amount_second': None,
  'amount_third': None},
 {'category': 'Behaviour At Work',
  'name': 'Indecent dressing',
  'sort_order': 28,
  'penalty_first': '₦2,000 with warning',
  'penalty_second': '₦5,000',
  'penalty_third': '₦10,000',
  'amount_first': 2000,
  'amount_second': 5000,
  'amount_third': 10000},
 {'category': 'Behaviour At Work',
  'name': 'Quarreling / Provocation',
  'sort_order': 29,
  'penalty_first': '₦2,000',
  'penalty_second': '₦4,000',
  'penalty_third': '₦6,000',
  'amount_first': 2000,
  'amount_second': 4000,
  'amount_third': 6000},
 {'category': 'Behaviour At Work',
  'name': 'Fighting',
  'sort_order': 30,
  'penalty_first': 'Dismissal',
  'penalty_second': '',
  'penalty_third': '',
  'amount_first': None,
  'amount_second': None,
  'amount_third': None},
 {'category': 'Behaviour At Work',
  'name': 'Disregard/Disrespect to superiors',
  'sort_order': 31,
  'penalty_first': '₦5,000',
  'penalty_second': '₦7,000',
  'penalty_third': '6 days suspension',
  'amount_first': 5000,
  'amount_second': 7000,
  'amount_third': None},
 {'category': 'Behaviour At Work',
  'name': 'Stealing',
  'sort_order': 32,
  'penalty_first': 'Dismissed without pay & imprisonment',
  'penalty_second': 'NIL',
  'penalty_third': '',
  'amount_first': None,
  'amount_second': None,
  'amount_third': None},
 {'category': 'Behaviour At Work',
  'name': 'Insubordination',
  'sort_order': 33,
  'penalty_first': '₦3,000',
  'penalty_second': '₦5,000',
  'penalty_third': '4 days suspension',
  'amount_first': 3000,
  'amount_second': 5000,
  'amount_third': None},
 {'category': 'Behaviour At Work',
  'name': 'Fighting with weapons',
  'sort_order': 34,
  'penalty_first': 'Dismissed without pay & imprisonment',
  'penalty_second': 'NIL',
  'penalty_third': '',
  'amount_first': None,
  'amount_second': None,
  'amount_third': None},
 {'category': 'Behaviour At Work',
  'name': 'Non-consented sexual activities (rape, recording) / Falsely accusing another party of rape',
  'sort_order': 35,
  'penalty_first': '100% of one month salary & imprisonment',
  'penalty_second': 'NIL',
  'penalty_third': '',
  'amount_first': None,
  'amount_second': None,
  'amount_third': None},
 {'category': 'Behaviour At Work',
  'name': 'Found guilty of sexual harassment either by colleague or supervisors',
  'sort_order': 36,
  'penalty_first': 'Dismissal',
  'penalty_second': '',
  'penalty_third': '',
  'amount_first': None,
  'amount_second': None,
  'amount_third': None},
 {'category': 'Behaviour At Work',
  'name': 'Working whilst drunk or high',
  'sort_order': 37,
  'penalty_first': 'Immediate dismissal',
  'penalty_second': '',
  'penalty_third': '',
  'amount_first': None,
  'amount_second': None,
  'amount_third': None},
 {'category': 'Behaviour At Work',
  'name': 'Cultism or Diabolic practices',
  'sort_order': 38,
  'penalty_first': 'Immediate dismissal',
  'penalty_second': 'NIL',
  'penalty_third': '',
  'amount_first': None,
  'amount_second': None,
  'amount_third': None},
 {'category': 'Department',
  'name': 'Working slowly to receive payment for overtime',
  'sort_order': 39,
  'penalty_first': 'No overtime will be paid',
  'penalty_second': '',
  'penalty_third': '',
  'amount_first': None,
  'amount_second': None,
  'amount_third': None},
 {'category': 'Department',
  'name': 'Talking to the scrap suppliers, escorts or drivers',
  'sort_order': 40,
  'penalty_first': '₦20,000',
  'penalty_second': 'Dismissal',
  'penalty_third': '',
  'amount_first': 20000,
  'amount_second': None,
  'amount_third': None},
 {'category': 'Department',
  'name': 'Producing bad billets or profiles due to carelessness',
  'sort_order': 41,
  'penalty_first': '₦1,000/basket or per billet',
  'penalty_second': '₦2,000/basket',
  'penalty_third': '₦10,000',
  'amount_first': None,
  'amount_second': None,
  'amount_third': 10000},
 {'category': 'Department',
  'name': 'Misplacement of machinery remote controls or work tools',
  'sort_order': 42,
  'penalty_first': 'Cost of replacement borne by team',
  'penalty_second': 'Cost of replacement borne by team',
  'penalty_third': 'Cost of replacement borne by team',
  'amount_first': None,
  'amount_second': None,
  'amount_third': None},
 {'category': 'Department',
  'name': 'Leaving work station dirty',
  'sort_order': 43,
  'penalty_first': '₦500 per team member, 1000 for team lead',
  'penalty_second': '₦1,500 per team member, ₦3,000 for team lead',
  'penalty_third': '₦3,000, ₦5,000 for team lead',
  'amount_first': None,
  'amount_second': None,
  'amount_third': None},
 {'category': 'Department',
  'name': 'Hiding rejects or sand in scrap / Selling rejects',
  'sort_order': 44,
  'penalty_first': 'Dismissed and handed to the police',
  'penalty_second': 'NIL',
  'penalty_third': '',
  'amount_first': None,
  'amount_second': None,
  'amount_third': None},
 {'category': 'Department',
  'name': 'Iron found in the oven',
  'sort_order': 45,
  'penalty_first': '₦1,000 per team member',
  'penalty_second': '₦2,000 per team member',
  'penalty_third': '₦3,000 per team member',
  'amount_first': None,
  'amount_second': None,
  'amount_third': None},
 {'category': 'Department',
  'name': 'Driving forklifts roughly or Overspeeding',
  'sort_order': 46,
  'penalty_first': '₦5000, 20% of repair cost if damaged',
  'penalty_second': '₦10,000',
  'penalty_third': '4 days suspension',
  'amount_first': None,
  'amount_second': 10000,
  'amount_third': None},
 {'category': 'Department',
  'name': 'Relaxing on forklift',
  'sort_order': 47,
  'penalty_first': '₦2,000',
  'penalty_second': '₦5,000',
  'penalty_third': '',
  'amount_first': 2000,
  'amount_second': 5000,
  'amount_third': None},
 {'category': 'Department',
  'name': 'Overheating furnaces unnecessarily',
  'sort_order': 48,
  'penalty_first': '₦2,000',
  'penalty_second': '₦5,000',
  'penalty_third': '₦10,000',
  'amount_first': 2000,
  'amount_second': 5000,
  'amount_third': 10000},
 {'category': 'Department',
  'name': 'Wrong coding of billets',
  'sort_order': 49,
  'penalty_first': '₦500',
  'penalty_second': '₦1,000',
  'penalty_third': '₦3,000',
  'amount_first': 500,
  'amount_second': 1000,
  'amount_third': 3000},
 {'category': 'Department',
  'name': 'Pouring ashes without spreading out old ones',
  'sort_order': 50,
  'penalty_first': '₦5,000',
  'penalty_second': '₦10,000',
  'penalty_third': '₦15,000',
  'amount_first': 5000,
  'amount_second': 10000,
  'amount_third': 15000},
 {'category': 'Department',
  'name': 'Using worn-out molds',
  'sort_order': 51,
  'penalty_first': '₦1,000',
  'penalty_second': '₦2,000',
  'penalty_third': '₦4,000',
  'amount_first': 1000,
  'amount_second': 2000,
  'amount_third': 4000},
 {'category': 'Department',
  'name': 'Keeping molds inside the extrusion oven after use',
  'sort_order': 52,
  'penalty_first': '₦2,000',
  'penalty_second': '₦5,000',
  'penalty_third': '₦10,000',
  'amount_first': 2000,
  'amount_second': 5000,
  'amount_third': 10000},
 {'category': 'Department',
  'name': 'Damaging molds due to unnecessary mistakes',
  'sort_order': 53,
  'penalty_first': '₦5,000',
  'penalty_second': '₦7,000',
  'penalty_third': '₦9,000',
  'amount_first': 5000,
  'amount_second': 7000,
  'amount_third': 9000},
 {'category': 'Department',
  'name': 'Unnecessary delays in mold preparation',
  'sort_order': 54,
  'penalty_first': '₦1,000',
  'penalty_second': '₦2,000',
  'penalty_third': '₦5,000',
  'amount_first': 1000,
  'amount_second': 2000,
  'amount_third': 5000},
 {'category': 'Department',
  'name': 'Not reporting bad maintenance of molds',
  'sort_order': 55,
  'penalty_first': '₦1,000',
  'penalty_second': '₦2,000',
  'penalty_third': '₦5,000',
  'amount_first': 1000,
  'amount_second': 2000,
  'amount_third': 5000},
 {'category': 'Department',
  'name': 'Sending unplied profiles to ageing',
  'sort_order': 56,
  'penalty_first': '₦1,000',
  'penalty_second': '₦3,000',
  'penalty_third': '₦5,000',
  'amount_first': 1000,
  'amount_second': 3000,
  'amount_third': 5000},
 {'category': 'Department',
  'name': 'Damage to extrusion cylinder/mold',
  'sort_order': 57,
  'penalty_first': '10% of cost',
  'penalty_second': '30% of cost',
  'penalty_third': '50% of cost',
  'amount_first': None,
  'amount_second': None,
  'amount_third': None},
 {'category': 'Department',
  'name': 'Cutting profiles to the wrong length after extrusion',
  'sort_order': 58,
  'penalty_first': '20% of production cost shared among the team',
  'penalty_second': '20% of production cost shared among the team',
  'penalty_third': '20% of production cost shared among the team',
  'amount_first': None,
  'amount_second': None,
  'amount_third': None},
 {'category': 'Department',
  'name': 'Selling billets offcuts',
  'sort_order': 59,
  'penalty_first': 'Dismissed without pay and handed to the police',
  'penalty_second': '',
  'penalty_third': '',
  'amount_first': None,
  'amount_second': None,
  'amount_third': None},
 {'category': 'Department',
  'name': 'Failure to load billets into the oven for the next shift',
  'sort_order': 60,
  'penalty_first': '₦2,000',
  'penalty_second': '₦5,000',
  'penalty_third': '₦10,000',
  'amount_first': 2000,
  'amount_second': 5000,
  'amount_third': 10000},
 {'category': 'Department',
  'name': 'Unauthorised switch off of machine heating',
  'sort_order': 61,
  'penalty_first': '₦2,000',
  'penalty_second': '₦5,000',
  'penalty_third': '₦7,000',
  'amount_first': 2000,
  'amount_second': 5000,
  'amount_third': 7000},
 {'category': 'Department',
  'name': 'Loosely tying baskets to crane leading to injury/damage.',
  'sort_order': 62,
  'penalty_first': '20% of the loss costs or medical bill',
  'penalty_second': '30% of loss costs or medical bill',
  'penalty_third': '50% of loss costs or medical bill',
  'amount_first': None,
  'amount_second': None,
  'amount_third': None},
 {'category': 'Department',
  'name': 'Wrong use of crane leading to damage or fault in crane',
  'sort_order': 63,
  'penalty_first': '10% cost of repair',
  'penalty_second': '20% cost of repair',
  'penalty_third': '50% cost of repair',
  'amount_first': None,
  'amount_second': None,
  'amount_third': None},
 {'category': 'Department',
  'name': 'Not monitoring ageing oven',
  'sort_order': 64,
  'penalty_first': '₦2,000',
  'penalty_second': '₦5,000',
  'penalty_third': '₦10,000',
  'amount_first': 2000,
  'amount_second': 5000,
  'amount_third': 10000},
 {'category': 'Department',
  'name': 'Failure to report defective materials',
  'sort_order': 65,
  'penalty_first': '₦2,000',
  'penalty_second': '₦3,000',
  'penalty_third': '₦5,000',
  'amount_first': 2000,
  'amount_second': 3000,
  'amount_third': 5000},
 {'category': 'Department',
  'name': 'Spotted coating due to poor powder room cleaning',
  'sort_order': 66,
  'penalty_first': '₦2,000 per team member',
  'penalty_second': '₦3,000 per team member',
  'penalty_third': '₦5,000 per team member',
  'amount_first': None,
  'amount_second': None,
  'amount_third': None},
 {'category': 'Department',
  'name': 'Not inspecting profiles after coating for defects',
  'sort_order': 67,
  'penalty_first': '₦1,000',
  'penalty_second': '₦2,000',
  'penalty_third': '₦5,000',
  'amount_first': 1000,
  'amount_second': 2000,
  'amount_third': 5000},
 {'category': 'Department',
  'name': 'Allowing powder coating hangers into booth without profiles',
  'sort_order': 68,
  'penalty_first': '₦500 per team member',
  'penalty_second': '₦500 per team member',
  'penalty_third': '₦500 per team member',
  'amount_first': None,
  'amount_second': None,
  'amount_third': None},
 {'category': 'Department',
  'name': 'Unauthorised stopping of powder coating line',
  'sort_order': 69,
  'penalty_first': '₦3,000',
  'penalty_second': '1 week salary',
  'penalty_third': 'Dismissal',
  'amount_first': 3000,
  'amount_second': None,
  'amount_third': None},
 {'category': 'Department',
  'name': 'Poor handling of material',
  'sort_order': 70,
  'penalty_first': '₦3,000',
  'penalty_second': '₦5,000',
  'penalty_third': '₦10,000',
  'amount_first': 3000,
  'amount_second': 5000,
  'amount_third': 10000},
 {'category': 'Department',
  'name': 'Incorrect labeling of profiles',
  'sort_order': 71,
  'penalty_first': '10% cost of material wasted',
  'penalty_second': '20% cost of material wasted',
  'penalty_third': '40% cost of material wasted',
  'amount_first': None,
  'amount_second': None,
  'amount_third': None},
 {'category': 'Department',
  'name': 'Mixing different materials in a bundle',
  'sort_order': 72,
  'penalty_first': '₦3,000',
  'penalty_second': '₦5,000',
  'penalty_third': '₦10,000',
  'amount_first': 3000,
  'amount_second': 5000,
  'amount_third': 10000},
 {'category': 'Department',
  'name': 'Sitting or lying down on profiles packed in the FPS',
  'sort_order': 73,
  'penalty_first': '₦1,000',
  'penalty_second': '₦2,000',
  'penalty_third': '₦5,000',
  'amount_first': 1000,
  'amount_second': 2000,
  'amount_third': 5000},
 {'category': 'Department',
  'name': 'Packing uneven or misaligned profiles in a bundle',
  'sort_order': 74,
  'penalty_first': '₦500 per team member per bundle',
  'penalty_second': '₦1000 per team member per bundle',
  'penalty_third': '₦2000 per team member per bundle',
  'amount_first': None,
  'amount_second': None,
  'amount_third': None},
 {'category': 'Department',
  'name': 'Mishandling or throwing profiles when loading',
  'sort_order': 75,
  'penalty_first': '₦500',
  'penalty_second': '₦1,000',
  'penalty_third': '₦2,000',
  'amount_first': 500,
  'amount_second': 1000,
  'amount_third': 2000},
 {'category': 'Task Management',
  'name': 'Failure to execute assigned tasks',
  'sort_order': 76,
  'penalty_first': 'Written Warning',
  'penalty_second': '₦2,000',
  'penalty_third': '₦5,000',
  'amount_first': None,
  'amount_second': 2000,
  'amount_third': 5000},
 {'category': 'Task Management',
  'name': 'Negligence to duty/Negligence with threat to life',
  'sort_order': 77,
  'penalty_first': '₦3,000/1 week suspension',
  'penalty_second': '₦10,000/Dismissal',
  'penalty_third': '1 week suspension/',
  'amount_first': None,
  'amount_second': None,
  'amount_third': None},
 {'category': 'Task Management',
  'name': 'Failure to complete tasks',
  'sort_order': 78,
  'penalty_first': 'Written Warning',
  'penalty_second': '₦2,000',
  'penalty_third': '₦5,000',
  'amount_first': None,
  'amount_second': 2000,
  'amount_third': 5000},
 {'category': 'Task Management',
  'name': 'Failure to hand over properly during shift change',
  'sort_order': 79,
  'penalty_first': '₦2,000',
  'penalty_second': '₦5,000',
  'penalty_third': '1 week salary',
  'amount_first': 2000,
  'amount_second': 5000,
  'amount_third': None},
 {'category': 'Task Management',
  'name': 'No proper, timely feedback on assigned tasks',
  'sort_order': 80,
  'penalty_first': 'Written Warning',
  'penalty_second': '₦2,000',
  'penalty_third': '₦5,000',
  'amount_first': None,
  'amount_second': 2000,
  'amount_third': 5000},
 {'category': 'Behaviour In The Hostel',
  'name': 'Having the opposite gender in the room',
  'sort_order': 81,
  'penalty_first': '₦30,000 for all except reporter',
  'penalty_second': '₦40,000',
  'penalty_third': 'Dismissal',
  'amount_first': None,
  'amount_second': 40000,
  'amount_third': None},
 {'category': 'Behaviour In The Hostel',
  'name': 'Entering hostel without hostel pass during work hours',
  'sort_order': 82,
  'penalty_first': '1 day salary',
  'penalty_second': '2 days salary',
  'penalty_third': '4 days suspension',
  'amount_first': None,
  'amount_second': None,
  'amount_third': None},
 {'category': 'Behaviour In The Hostel',
  'name': 'Unauthorized guests in the hostel',
  'sort_order': 83,
  'penalty_first': '₦3,000',
  'penalty_second': '₦5,000',
  'penalty_third': 'Eviction from the hostel',
  'amount_first': 3000,
  'amount_second': 5000,
  'amount_third': None},
 {'category': 'Behaviour In The Hostel',
  'name': 'Improper disposal of waste',
  'sort_order': 84,
  'penalty_first': 'Sweep the whole hostel',
  'penalty_second': 'Clean all gutters in the company',
  'penalty_third': 'Work as housekeeper for 4 days',
  'amount_first': None,
  'amount_second': None,
  'amount_third': None},
 {'category': 'Behaviour In The Hostel',
  'name': 'Damaging hostel property',
  'sort_order': 85,
  'penalty_first': 'Half the replacement cost per roommate.',
  'penalty_second': 'Full replacement cost per roommate.',
  'penalty_third': 'Eviction from the hostel',
  'amount_first': None,
  'amount_second': None,
  'amount_third': None},
 {'category': 'Behaviour In The Hostel',
  'name': 'Tampering with electrical installations or wiring (bulbs, panels, fans etc)',
  'sort_order': 86,
  'penalty_first': '₦5,000',
  'penalty_second': '₦7,500',
  'penalty_third': '₦10,000',
  'amount_first': 5000,
  'amount_second': 7500,
  'amount_third': 10000},
 {'category': 'Behaviour In The Hostel',
  'name': 'Switching off the hallway light',
  'sort_order': 87,
  'penalty_first': '₦5,000',
  'penalty_second': '₦7,500',
  'penalty_third': '₦10,000',
  'amount_first': 5000,
  'amount_second': 7500,
  'amount_third': 10000},
 {'category': 'Behaviour In The Hostel',
  'name': 'Playing loud music',
  'sort_order': 88,
  'penalty_first': 'Seized until exit',
  'penalty_second': 'Seized again + ₦10,000',
  'penalty_third': 'Eviction & confiscation of device',
  'amount_first': None,
  'amount_second': 10000,
  'amount_third': None},
 {'category': 'Behaviour In The Hostel',
  'name': 'Spreading clothes on the rails',
  'sort_order': 89,
  'penalty_first': '₦500',
  'penalty_second': '₦1,000',
  'penalty_third': '₦2,000',
  'amount_first': 500,
  'amount_second': 1000,
  'amount_third': 2000},
 {'category': 'Behaviour In The Hostel',
  'name': 'Spreading clothes inside the room',
  'sort_order': 90,
  'penalty_first': '₦500',
  'penalty_second': '₦1,000',
  'penalty_third': '₦2,000',
  'amount_first': 500,
  'amount_second': 1000,
  'amount_third': 2000},
 {'category': 'Behaviour In The Hostel',
  'name': 'Hiding company-issued items (bedsheets & co.)',
  'sort_order': 91,
  'penalty_first': '₦3,000',
  'penalty_second': '₦6,000',
  'penalty_third': '₦10,000',
  'amount_first': 3000,
  'amount_second': 6000,
  'amount_third': 10000},
 {'category': 'Behaviour In The Hostel',
  'name': 'Smoking in the hostel',
  'sort_order': 92,
  'penalty_first': '₦10,000',
  'penalty_second': '₦20,000',
  'penalty_third': 'Eviction from the hostel',
  'amount_first': 10000,
  'amount_second': 20000,
  'amount_third': None},
 {'category': 'Behaviour In The Hostel',
  'name': 'Failure to adhere to curfew times',
  'sort_order': 93,
  'penalty_first': '₦1,000',
  'penalty_second': '₦2,000',
  'penalty_third': '₦5,000',
  'amount_first': 1000,
  'amount_second': 2000,
  'amount_third': 5000},
 {'category': 'Behaviour In The Hostel',
  'name': 'Unauthorized room changes',
  'sort_order': 94,
  'penalty_first': '₦5,000 with Warning',
  'penalty_second': '₦10,000',
  'penalty_third': 'Eviction',
  'amount_first': 5000,
  'amount_second': 10000,
  'amount_third': None},
 {'category': 'Behaviour In The Hostel',
  'name': 'Absent from work and being in hostel without permission',
  'sort_order': 95,
  'penalty_first': '₦10,000',
  'penalty_second': '₦15,000',
  'penalty_third': '6 days suspension',
  'amount_first': 10000,
  'amount_second': 15000,
  'amount_third': None},
 {'category': 'Behaviour In The Hostel',
  'name': 'Leaving electrical appliances on',
  'sort_order': 96,
  'penalty_first': '₦1,000',
  'penalty_second': '₦3,000',
  'penalty_third': '₦5,000',
  'amount_first': 1000,
  'amount_second': 3000,
  'amount_third': 5000},
 {'category': 'Behaviour In The Hostel',
  'name': 'Leaving the kitchen dirty after use',
  'sort_order': 97,
  'penalty_first': '₦1,000',
  'penalty_second': '₦3,000',
  'penalty_third': '₦5,000',
  'amount_first': 1000,
  'amount_second': 3000,
  'amount_third': 5000},
 {'category': 'Behaviour In The Hostel',
  'name': 'Cooking inside the room',
  'sort_order': 98,
  'penalty_first': 'Seized until ₦5,000 is paid',
  'penalty_second': 'Equipment confiscated',
  'penalty_third': 'Eviction from the hostel',
  'amount_first': None,
  'amount_second': None,
  'amount_third': None},
 {'category': 'Behaviour In The Hostel',
  'name': 'Cooking or washing in the expatriates kitchen',
  'sort_order': 99,
  'penalty_first': '₦10,000',
  'penalty_second': '₦15,000',
  'penalty_third': 'Eviction from the hostel',
  'amount_first': 10000,
  'amount_second': 15000,
  'amount_third': None},
 {'category': 'Behaviour In The Hostel',
  'name': 'Dirty rooms, dirty toilets',
  'sort_order': 100,
  'penalty_first': '₦2,000 for each occupant',
  'penalty_second': '₦5,000 for each occupant',
  'penalty_third': '₦10,000',
  'amount_first': None,
  'amount_second': None,
  'amount_third': 10000},
 {'category': 'Behaviour In The Hostel',
  'name': 'Sexual activities in or around the Hostel or Premises',
  'sort_order': 101,
  'penalty_first': '₦30,000',
  'penalty_second': 'Sack',
  'penalty_third': '',
  'amount_first': 30000,
  'amount_second': None,
  'amount_third': None},
 {'category': 'Behaviour In The Hostel',
  'name': 'Stealing',
  'sort_order': 102,
  'penalty_first': 'Full cost of stolen item',
  'penalty_second': 'Eviction from the hostel',
  'penalty_third': '',
  'amount_first': None,
  'amount_second': None,
  'amount_third': None},
 {'category': 'Behaviour In The Hostel',
  'name': 'Blocking or stopping room inspections.',
  'sort_order': 103,
  'penalty_first': '₦2,000',
  'penalty_second': '₦5,000',
  'penalty_third': '₦10,000',
  'amount_first': 2000,
  'amount_second': 5000,
  'amount_third': 10000},
 {'category': 'Quality & Damages',
  'name': 'Damaging machines, building and other property',
  'sort_order': 104,
  'penalty_first': '20% of the repair costs',
  'penalty_second': '30% of the repair costs',
  'penalty_third': '50% of the repair costs',
  'amount_first': None,
  'amount_second': None,
  'amount_third': None},
 {'category': 'Quality & Damages',
  'name': 'Losing or damaging small tools and production materials',
  'sort_order': 105,
  'penalty_first': 'Cost for replacement',
  'penalty_second': 'Cost for replacement',
  'penalty_third': 'Cost of replacement',
  'amount_first': None,
  'amount_second': None,
  'amount_third': None},
 {'category': 'Quality & Damages',
  'name': 'Damaging colleagues’ property',
  'sort_order': 106,
  'penalty_first': 'Cost of repair or replacement',
  'penalty_second': 'Cost of repair or replacement',
  'penalty_third': 'Cost of repair or replacement',
  'amount_first': None,
  'amount_second': None,
  'amount_third': None},
 {'category': 'Leadership, Supervisory & Management',
  'name': 'Treating team members unfairly',
  'sort_order': 107,
  'penalty_first': '₦2,000',
  'penalty_second': '₦5,000',
  'penalty_third': '4 days suspension',
  'amount_first': 2000,
  'amount_second': 5000,
  'amount_third': None},
 {'category': 'Leadership, Supervisory & Management',
  'name': 'Bullying the opposite gender due to rejected advances',
  'sort_order': 108,
  'penalty_first': '₦3,000',
  'penalty_second': '₦5,000',
  'penalty_third': '6 days suspension',
  'amount_first': 3000,
  'amount_second': 5000,
  'amount_third': None},
 {'category': 'Leadership, Supervisory & Management',
  'name': 'Failure to hand over properly during shift change',
  'sort_order': 109,
  'penalty_first': '₦5,000',
  'penalty_second': '₦10,000',
  'penalty_third': '1 week suspension',
  'amount_first': 5000,
  'amount_second': 10000,
  'amount_third': None},
 {'category': 'Leadership, Supervisory & Management',
  'name': 'Bypassing safety or operational SOPs deliberately',
  'sort_order': 110,
  'penalty_first': 'Warning',
  'penalty_second': '₦5,000',
  'penalty_third': '₦7,000',
  'amount_first': None,
  'amount_second': 5000,
  'amount_third': 7000},
 {'category': 'Leadership, Supervisory & Management',
  'name': 'Neglecting to fill production or maintenance logs or incorrect records',
  'sort_order': 111,
  'penalty_first': '₦2,000',
  'penalty_second': '₦5,000',
  'penalty_third': '₦7,000',
  'amount_first': 2000,
  'amount_second': 5000,
  'amount_third': 7000},
 {'category': 'Leadership, Supervisory & Management',
  'name': 'Changing Standard of operating',
  'sort_order': 112,
  'penalty_first': '₦10,000',
  'penalty_second': '₦15,000',
  'penalty_third': '',
  'amount_first': 10000,
  'amount_second': 15000,
  'amount_third': None},
 {'category': 'Leadership, Supervisory & Management',
  'name': 'Poor supervision',
  'sort_order': 113,
  'penalty_first': 'Query and warning letter',
  'penalty_second': '₦5,000',
  'penalty_third': '₦10,000',
  'amount_first': None,
  'amount_second': 5000,
  'amount_third': 10000},
 {'category': 'Information & Data',
  'name': 'Misuse of company data or confidential information',
  'sort_order': 114,
  'penalty_first': 'Written Warning',
  'penalty_second': 'Final Warning with 1 week Suspension',
  'penalty_third': 'Dismissal with legal action',
  'amount_first': None,
  'amount_second': None,
  'amount_third': None},
 {'category': 'Information & Data',
  'name': 'Unauthorised Use of company WiFi',
  'sort_order': 115,
  'penalty_first': '₦5,000',
  'penalty_second': 'Written warning with ₦10,000',
  'penalty_third': '1 week suspension',
  'amount_first': 5000,
  'amount_second': 10000,
  'amount_third': None},
 {'category': 'Information & Data',
  'name': 'Using company devices to access pornography or illegal content',
  'sort_order': 116,
  'penalty_first': 'Written Warning with 1 week suspension',
  'penalty_second': '2 Weeks Suspension',
  'penalty_third': 'Immediate dismissal',
  'amount_first': None,
  'amount_second': None,
  'amount_third': None},
 {'category': 'Information & Data',
  'name': 'Unauthorized sharing of company information with outsiders',
  'sort_order': 117,
  'penalty_first': 'Final warning with 1 week suspension',
  'penalty_second': 'Immediate dismissal with legal action',
  'penalty_third': '',
  'amount_first': None,
  'amount_second': None,
  'amount_third': None}]

REWARDS = [{'category': 'Attendance and Punctuality',
  'name': 'No absence',
  'sort_order': 1,
  'reward_first': '₦1,000',
  'reward_second': '₦2,000',
  'amount_first': 1000,
  'amount_second': 2000,
  'auto_rule': 'no_absence'},
 {'category': 'Attendance and Punctuality',
  'name': 'No lateness',
  'sort_order': 2,
  'reward_first': '₦2,000',
  'reward_second': '₦3,000',
  'amount_first': 2000,
  'amount_second': 3000,
  'auto_rule': 'no_lateness'},
 {'category': 'Good Work Ethics',
  'name': 'Giving ideas that save costs',
  'sort_order': 3,
  'reward_first': '10% of cost saved by idea',
  'reward_second': '20% of cost saved by idea',
  'amount_first': None,
  'amount_second': None,
  'auto_rule': ''},
 {'category': 'Good Work Ethics',
  'name': 'Volunteering for additional tasks',
  'sort_order': 4,
  'reward_first': '₦5,000',
  'reward_second': '₦7,000',
  'amount_first': 5000,
  'amount_second': 7000,
  'auto_rule': ''},
 {'category': 'Good Work Ethics',
  'name': 'Maintaining good work ethics',
  'sort_order': 5,
  'reward_first': '₦1,000',
  'reward_second': '₦2,000',
  'amount_first': 1000,
  'amount_second': 2000,
  'auto_rule': ''},
 {'category': 'Good Work Ethics',
  'name': 'Reporting unsafe hazards in the factory or hostel',
  'sort_order': 6,
  'reward_first': '₦2,000',
  'reward_second': '₦3,000',
  'amount_first': 2000,
  'amount_second': 3000,
  'auto_rule': ''},
 {'category': 'Good Work Ethics',
  'name': 'Reporting fraudulent activity in the factory',
  'sort_order': 7,
  'reward_first': '₦2,000',
  'reward_second': '₦3,000',
  'amount_first': 2000,
  'amount_second': 3000,
  'auto_rule': ''},
 {'category': 'Good Work Ethics',
  'name': 'Maintaining clean work areas',
  'sort_order': 8,
  'reward_first': '₦1,000',
  'reward_second': '₦2,000',
  'amount_first': 1000,
  'amount_second': 2000,
  'auto_rule': ''},
 {'category': 'Performance-Based',
  'name': 'Exceeding individual or team production targets.',
  'sort_order': 9,
  'reward_first': '₦2,000 per team member',
  'reward_second': '₦5,000 per team member',
  'amount_first': None,
  'amount_second': None,
  'auto_rule': ''},
 {'category': 'Performance-Based',
  'name': 'Exceptional Leadership',
  'sort_order': 10,
  'reward_first': '₦2,000',
  'reward_second': '₦5,000',
  'amount_first': 2000,
  'amount_second': 5000,
  'auto_rule': ''},
 {'category': 'Performance-Based',
  'name': 'Employee of the Month',
  'sort_order': 11,
  'reward_first': 'Gift',
  'reward_second': 'Gift',
  'amount_first': None,
  'amount_second': None,
  'auto_rule': ''},
 {'category': 'Performance-Based',
  'name': 'Bi-annual team success review',
  'sort_order': 12,
  'reward_first': '₦2,000 per team member on being successful',
  'reward_second': '₦3,000 per team member on being successful',
  'amount_first': None,
  'amount_second': None,
  'auto_rule': ''},
 {'category': 'Performance-Based',
  'name': 'Outstanding Contributor of the Month',
  'sort_order': 13,
  'reward_first': 'Gift',
  'reward_second': 'Gift',
  'amount_first': None,
  'amount_second': None,
  'auto_rule': ''},
 {'category': 'Employee Welfare',
  'name': 'Employees that has worked for 6+ months',
  'sort_order': 14,
  'reward_first': 'Two meals daily',
  'reward_second': 'NIL',
  'amount_first': None,
  'amount_second': None,
  'auto_rule': ''},
 {'category': 'Employee Welfare',
  'name': 'Employees working in high risk departments',
  'sort_order': 15,
  'reward_first': 'Milk biweekly',
  'reward_second': 'NIL',
  'amount_first': None,
  'amount_second': None,
  'auto_rule': ''},
 {'category': 'Employee Welfare',
  'name': 'Injuries and illnesses',
  'sort_order': 16,
  'reward_first': 'Company nurse For severe injuries, hospital bills coverage',
  'reward_second': 'NIL',
  'amount_first': None,
  'amount_second': None,
  'auto_rule': ''},
 {'category': 'Career Growth',
  'name': 'Performance reviews with opportunities for salary adjustments',
  'sort_order': 17,
  'reward_first': 'Increment upon successful review',
  'reward_second': 'NIL',
  'amount_first': None,
  'amount_second': None,
  'auto_rule': ''},
 {'category': 'Career Growth',
  'name': 'Promotion Opportunities to leadership roles',
  'sort_order': 18,
  'reward_first': 'Increment',
  'reward_second': 'NIL',
  'amount_first': None,
  'amount_second': None,
  'auto_rule': ''},
 {'category': 'Safety Compliance',
  'name': 'Maintaining an accident-free team.',
  'sort_order': 19,
  'reward_first': '₦2,000',
  'reward_second': '₦5,000',
  'amount_first': 2000,
  'amount_second': 5000,
  'auto_rule': ''}]
