# Generated by Django 6.1 on 2026-09-02 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0004_alter_leaverequest_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leavepolicy',
            options={'ordering': ['leave_type__name']},
        ),
        migrations.RemoveField(
            model_name='leavepolicy',
            name='department',
        ),
        migrations.RemoveField(
            model_name='leavepolicy',
            name='employment_type',
        ),
        migrations.RemoveField(
            model_name='leavepolicy',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='leavepolicy',
            name='maximum_years_of_service',
        ),
        migrations.RemoveField(
            model_name='leavepolicy',
            name='minimum_years_of_service',
        ),
        migrations.RemoveField(
            model_name='leavepolicy',
            name='position',
        ),
        migrations.AlterField(
            model_name='leavepolicy',
            name='employment_category',
            field=models.CharField(choices=[('staff', 'Staff'), ('management', 'Management'), ('executive', 'Executive')], max_length=20, null=True),
        ),
        migrations.AddConstraint(
            model_name='leavepolicy',
            constraint=models.UniqueConstraint(fields=('leave_type', 'employment_category'), name='unique_leave_policy_per_category'),
        ),
    ]
