# Generated by Django 6.1 on 2026-09-02 10:51

from django.db import migrations, models


def create_type_based_policy_defaults(apps, schema_editor):
    """Keep legacy category policies for reference and add missing HR defaults."""
    LeaveType = apps.get_model("leave", "LeaveType")
    LeavePolicy = apps.get_model("leave", "LeavePolicy")

    # Category policies cannot be mapped reliably to an employment type. Retain
    # them as inactive, unassigned records rather than silently changing access.
    LeavePolicy.objects.filter(
        employment_type__isnull=True,
        is_active=True,
    ).update(is_active=False)

    leave_type_defaults = [
        {
            "code": "ANNUAL",
            "name": "Annual Leave",
            "description": "Configurable annual paid leave entitlement.",
            "default_days": "15.00",
            "requires_approval": True,
            "is_paid": True,
            "color": "#2563EB",
        },
        {
            "code": "SICK",
            "name": "Sick Leave",
            "description": "Configurable paid sick leave entitlement.",
            "default_days": "5.00",
            "requires_approval": True,
            "is_paid": True,
            "color": "#DC2626",
        },
        {
            "code": "MATERNITY",
            "name": "Maternity Leave",
            "description": "Configurable maternity leave entitlement.",
            "default_days": "84.00",
            "requires_approval": True,
            "is_paid": True,
            "color": "#DB2777",
        },
        {
            "code": "PATERNITY",
            "name": "Paternity Leave",
            "description": "Configurable paternity leave entitlement.",
            "default_days": "5.00",
            "requires_approval": True,
            "is_paid": True,
            "color": "#7C3AED",
        },
        {
            "code": "BEREAVEMENT",
            "name": "Compassionate/Bereavement Leave",
            "description": "Configurable compassionate leave entitlement.",
            "default_days": "3.00",
            "requires_approval": True,
            "is_paid": True,
            "color": "#475569",
        },
        {
            "code": "STUDY",
            "name": "Study/Examination Leave",
            "description": "Configurable study or examination leave entitlement.",
            "default_days": "5.00",
            "requires_approval": True,
            "is_paid": True,
            "color": "#0891B2",
        },
        {
            "code": "UNPAID",
            "name": "Unpaid Leave",
            "description": "Configurable unpaid leave entitlement.",
            "default_days": "30.00",
            "requires_approval": True,
            "is_paid": False,
            "color": "#64748B",
        },
    ]

    leave_types = {}
    for defaults in leave_type_defaults:
        # Do not overwrite an administrator-created type that uses either the
        # standard code or standard name, including the existing Sick Leave.
        leave_type = (
            LeaveType.objects.filter(code=defaults["code"]).first()
            or LeaveType.objects.filter(name=defaults["name"]).first()
        )
        if leave_type is None:
            leave_type = LeaveType.objects.create(**defaults)
        leave_types[defaults["code"]] = leave_type

    policy_defaults = [
        ("ANNUAL", "permanent", "15.00", True, True),
        ("ANNUAL", "contract", "10.00", True, True),
        ("ANNUAL", "nysc", "10.00", True, True),
        ("ANNUAL", "expatriate", "20.00", True, True),
        ("SICK", "permanent", "5.00", True, True),
        ("SICK", "contract", "3.00", True, True),
        ("SICK", "intern", "2.00", True, True),
        ("SICK", "nysc", "3.00", True, True),
        ("SICK", "expatriate", "5.00", True, True),
        ("MATERNITY", "permanent", "84.00", True, True),
        ("MATERNITY", "contract", "84.00", True, True),
        ("MATERNITY", "expatriate", "84.00", True, True),
        ("PATERNITY", "permanent", "5.00", True, True),
        ("PATERNITY", "contract", "3.00", True, True),
        ("PATERNITY", "expatriate", "5.00", True, True),
        ("BEREAVEMENT", "permanent", "3.00", True, True),
        ("BEREAVEMENT", "contract", "3.00", True, True),
        ("BEREAVEMENT", "nysc", "3.00", True, True),
        ("BEREAVEMENT", "expatriate", "3.00", True, True),
        ("STUDY", "permanent", "5.00", True, True),
        ("STUDY", "intern", "3.00", True, True),
        ("STUDY", "nysc", "5.00", True, True),
        ("UNPAID", "permanent", "30.00", True, False),
        ("UNPAID", "contract", "30.00", True, False),
        ("UNPAID", "casual", "30.00", True, False),
        ("UNPAID", "intern", "30.00", True, False),
        ("UNPAID", "nysc", "30.00", True, False),
        ("UNPAID", "expatriate", "30.00", True, False),
    ]

    for code, employment_type, allocated_days, requires_approval, is_paid in policy_defaults:
        LeavePolicy.objects.get_or_create(
            leave_type=leave_types[code],
            employment_type=employment_type,
            defaults={
                "allocated_days": allocated_days,
                "requires_approval": requires_approval,
                "is_paid": is_paid,
                "is_active": True,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0005_alter_leavepolicy_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='leavepolicy',
            name='unique_leave_policy_per_category',
        ),
        migrations.AddField(
            model_name='leavepolicy',
            name='employment_type',
            field=models.CharField(choices=[('permanent', 'Permanent'), ('contract', 'Contract'), ('casual', 'Casual'), ('intern', 'Intern'), ('nysc', 'NYSC'), ('expatriate', 'Expatriate')], max_length=20, null=True),
        ),
        migrations.AddConstraint(
            model_name='leavepolicy',
            constraint=models.UniqueConstraint(fields=('leave_type', 'employment_type'), name='unique_leave_policy_per_type'),
        ),
        migrations.RemoveField(
            model_name='leavepolicy',
            name='employment_category',
        ),
        migrations.RunPython(create_type_based_policy_defaults, migrations.RunPython.noop),
    ]
