# Generated by Django 6.1 on 2026-09-22 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0006_remove_leavepolicy_unique_leave_policy_per_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leavepolicy',
            options={'ordering': ['leave_type__name'], 'permissions': [('manage_leave_policy', 'Can manage leave policy allocations')]},
        ),
    ]
