# Generated by Django 6.1 on 2026-10-02 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0007_alter_leavepolicy_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaverequest',
            options={'ordering': ['-created_at'], 'permissions': [('approve_leave', 'Can approve leave requests'), ('raise_leave_request', 'Can raise leave requests for employees')]},
        ),
    ]
