# Generated by Django 6.1 on 2026-09-03 19:32

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0007_alter_attendanceexception_exception_type'),
        ('employees', '0006_alter_biometricidentity_system'),
        ('payroll', '0003_payrolllineitem_unique_system_payroll_line_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MealDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MealEntitlementRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employment_type', models.CharField(blank=True, choices=[('permanent', 'Permanent'), ('contract', 'Contract'), ('casual', 'Casual'), ('intern', 'Intern'), ('nysc', 'NYSC'), ('expatriate', 'Expatriate')], max_length=20)),
                ('employment_category', models.CharField(blank=True, choices=[('staff', 'Staff'), ('management', 'Management'), ('executive', 'Executive')], max_length=20)),
                ('minimum_years_of_service', models.PositiveIntegerField(blank=True, null=True)),
                ('tickets_per_work_day', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('priority', models.PositiveIntegerField(default=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['priority', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MealTicketRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-effective_from', '-id'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeMealEntitlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tickets_per_work_day', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('reason', models.TextField()),
                ('is_exceptional_override', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meal_entitlements', to='employees.employee')),
                ('set_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meal_entitlements_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-effective_from', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MealEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('external_event_id', models.CharField(max_length=150)),
                ('verification_type', models.CharField(default='unknown', max_length=20)),
                ('source_system', models.CharField(max_length=50)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='meals.mealdevice')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meal_events', to='employees.employee')),
            ],
            options={
                'ordering': ['-timestamp', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MealCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField()),
                ('sequence_number', models.PositiveIntegerField()),
                ('entitlement_snapshot', models.PositiveIntegerField(default=0)),
                ('rate_snapshot', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('within_entitlement', 'Within entitlement'), ('excess', 'Excess'), ('rest_day', 'Not entitled - rest day')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meal_collections', to='employees.employee')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.shift')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='collection', to='meals.mealevent')),
            ],
            options={
                'ordering': ['-event__timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MealExcessException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField()),
                ('entitlement_snapshot', models.PositiveIntegerField()),
                ('collected_quantity', models.PositiveIntegerField()),
                ('excess_quantity', models.PositiveIntegerField()),
                ('rate_snapshot', models.DecimalField(decimal_places=2, max_digits=12)),
                ('proposed_deduction', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('cancelled', 'Cancelled'), ('deducted', 'Deducted')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meal_excess_exceptions', to='employees.employee')),
                ('payroll', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payroll.employeepayroll')),
                ('payroll_line_item', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payroll.payrolllineitem')),
                ('payroll_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payroll.payrollperiod')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meal_excess_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('record_meal_operations', 'Can record meal operations'), ('review_meal_excess', 'Can review meal excess deductions'), ('manage_meal_configuration', 'Can manage meal configuration')],
            },
        ),
        migrations.AddConstraint(
            model_name='mealevent',
            constraint=models.UniqueConstraint(fields=('device', 'external_event_id'), name='unique_meal_device_event'),
        ),
        migrations.AddConstraint(
            model_name='mealexcessexception',
            constraint=models.UniqueConstraint(fields=('employee', 'work_date'), name='unique_meal_excess_per_work_date'),
        ),
    ]
