# Generated by Django 6.1 on 2026-09-04 15:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_alter_biometricidentity_system'),
        ('meals', '0002_seed_initial_meal_rate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MealAbsencePenalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penalty_type', models.CharField(choices=[('single_absence', '1-day absence penalty'), ('two_consecutive', '2 consecutive-day absence penalty'), ('three_monthly', '3 absences in month - roster week penalty')], max_length=30)),
                ('source_absence_dates', models.JSONField(default=list, help_text='Attendance work dates that caused this meal penalty.')),
                ('tickets_to_reduce_per_work_day', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('work_days_to_apply', models.PositiveIntegerField(blank=True, help_text='Number of scheduled WORK days affected. May remain unset for a roster-week penalty until the roster is resolved.', null=True)),
                ('work_days_applied', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meal_absence_penalties_approved', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meal_absence_penalties', to='employees.employee')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
