# Generated by Django 6.1 on 2026-09-04 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_mealabsencepenalty'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealabsencepenalty',
            name='target_work_dates',
            field=models.JSONField(blank=True, default=list, help_text='Exact scheduled WORK dates selected for this penalty. Once resolved, these dates form the fixed penalty window.'),
        ),
    ]
