# Generated by Django 6.1 on 2026-09-17 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_alter_employee_options'),
        ('meals', '0004_mealabsencepenalty_target_work_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealentitlementrule',
            name='minimum_months_of_service',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mealentitlementrule',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meal_entitlement_rules', to='employees.position'),
        ),
    ]
