# Generated by Django 6.1 on 2026-09-18 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0007_mealcollection_void_reason_mealcollection_voided_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealexcessexception',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('cancelled', 'Cancelled'), ('deducted', 'Deducted'), ('declined', 'Declined')], default='pending', max_length=20),
        ),
    ]
