# Generated by Django 6.1 on 2026-09-18 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0008_alter_mealexcessexception_status'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='mealexcessexception',
            name='unique_meal_excess_per_work_date',
        ),
        migrations.AddField(
            model_name='mealcollection',
            name='excess_exception',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='meals.mealexcessexception'),
        ),
    ]
