# Generated by Django 6.1 on 2026-09-21 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_employee_gender'),
        ('meals', '0010_link_tickets_to_excess_decisions'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealTerminalUserState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_serial', models.CharField(max_length=100)),
                ('enabled', models.BooleanField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_terminal_states', to='employees.employee')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('employee', 'device_serial'), name='one_terminal_state_per_person_per_device')],
            },
        ),
    ]
