# Generated by Django 6.1 on 2026-09-21 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_employee_gender'),
        ('meals', '0011_mealterminaluserstate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MealExtraAuthorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField()),
                ('quantity', models.PositiveSmallIntegerField()),
                ('used', models.PositiveSmallIntegerField(default=0)),
                ('pays', models.CharField(choices=[('employee', 'Employee pays (deducted from pay)'), ('company', 'Company pays (no deduction)')], max_length=10)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('authorised_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meal_extra_authorizations', to='employees.employee')),
            ],
            options={
                'ordering': ['-work_date', '-created_at'],
            },
        ),
    ]
