# Generated by Django 6.1 on 2026-10-01 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0012_mealextraauthorization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealcollection',
            name='status',
            field=models.CharField(choices=[('within_entitlement', 'Within entitlement'), ('excess', 'Excess'), ('rest_day', 'Not entitled - rest day'), ('unscheduled', 'Not yet scheduled')], max_length=30),
        ),
    ]
