# Generated by Django 6.1 on 2026-10-05 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0013_alter_mealcollection_status'),
        ('payroll', '0005_employeepayroll_bank_details_snapshot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mealvendorpayment',
            options={'ordering': ['-payment_date', '-id'], 'permissions': [('view_meal_vendor_payments', 'Can view meal vendor payments'), ('record_meal_vendor_payments', 'Can record meal vendor payments')]},
        ),
        migrations.AddField(
            model_name='mealvendorpayment',
            name='covers_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mealvendorpayment',
            name='covers_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mealvendorpayment',
            name='payroll_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='meal_vendor_payments', to='payroll.payrollperiod'),
        ),
    ]
