# Generated by Django 6.1 on 2026-10-07 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_alter_employee_options'),
        ('meals', '0015_vendor_claims'),
        ('payroll', '0005_employeepayroll_bank_details_snapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MealChargeback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField()),
                ('quantity', models.PositiveIntegerField()),
                ('rate_snapshot', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.TextField()),
                ('reference', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('pending', 'Waiting for payroll'), ('deducted', 'Deducted from pay'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('pay_year', models.PositiveIntegerField()),
                ('pay_month', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.TextField(blank=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meal_chargebacks_cancelled', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meal_chargebacks_created', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meal_chargebacks', to='employees.employee')),
                ('payroll', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payroll.employeepayroll')),
                ('payroll_line_item', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payroll.payrolllineitem')),
                ('payroll_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payroll.payrollperiod')),
            ],
            options={
                'ordering': ['-work_date', '-id'],
                'permissions': [('charge_back_meal_tickets', 'Can charge back meal tickets to employees')],
            },
        ),
    ]
