# Generated by Django 6.1 on 2026-10-10 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_alter_employee_options'),
        ('meals', '0016_meal_chargebacks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MealAbsenceTicketReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField()),
                ('decision', models.CharField(choices=[('charged', 'Charged back'), ('waived', 'Not charged')], max_length=10)),
                ('reason', models.TextField()),
                ('decided_at', models.DateTimeField(auto_now=True)),
                ('chargeback', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='absence_reviews', to='meals.mealchargeback')),
                ('decided_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meal_absence_reviews', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meal_absence_reviews', to='employees.employee')),
            ],
            options={
                'ordering': ['-work_date', '-id'],
                'constraints': [models.UniqueConstraint(fields=('employee', 'work_date'), name='one_absence_ticket_review_per_person_day')],
            },
        ),
    ]
