# Generated by Django 6.1 on 2026-09-03 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_employee_employment_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biometricidentity',
            name='system',
            field=models.CharField(choices=[('yunatt', 'Yunatt / TIMY'), ('device', 'Direct Device'), ('vendor_flask_gateway', 'Vendor Flask Gateway'), ('other', 'Other')], default='yunatt', max_length=30),
        ),
    ]
