# Generated by Django 6.1 on 2026-09-17 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_alter_employee_department'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'permissions': [('view_salary', 'Can view and set employee basic salary')]},
        ),
    ]
