# Generated by Django 6.1 on 2026-09-17 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_alter_employee_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='exit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='external_accommodation_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='employee',
            name='lives_in_external_accommodation',
            field=models.BooleanField(default=False),
        ),
    ]
