# Generated by Django 6.1 on 2026-10-02 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_employee_gender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'permissions': [('view_salary', 'Can view and set employee basic salary'), ('view_bank_details', 'Can view and set employee bank details'), ('view_employee_statement', "Can generate an employee's monthly attendance and charges statement")]},
        ),
    ]
