from django.urls import path

from .bridge import MealVendorGatewayPunchBridgeAPIView
from .views import (
    MealExtraAuthorizationCancelAPIView,
    MealExtraAuthorizationListCreateAPIView,
    EmployeeMealsProfileAPIView,
    MealDeviceListAPIView,
    MealEntitlementListCreateAPIView,
    MealEntitlementRuleDetailAPIView,
    MealEntitlementRuleListCreateAPIView,
    MealExcessApproveAPIView,
    MealExcessBulkDecisionAPIView,
    MealCollectionVoidAPIView,
    MealExcessCancelAPIView,
    MealExcessDeclineAPIView,
    MealExcessPendingIdsAPIView,
    MealOperationsAPIView,
    MealReviewRemindersAPIView,
    MealTicketRateListCreateAPIView,
    MealVendorPaymentListCreateAPIView,
    MealVendorPeriodAPIView,
    MealChargebackCancelAPIView,
    MealChargebackListCreateAPIView,
    MealChargebackLookupAPIView,
    MealMultipleTicketsAPIView,
    MealShiftReportAPIView,
    MealShiftReportDecideAPIView,
    MealVendorClaimCreateAPIView,
    MealVendorClaimDetailAPIView,
    MealVendorSummaryAPIView,
)

urlpatterns = [
    path(
        "integrations/vendor-gateway/punches/",
        MealVendorGatewayPunchBridgeAPIView.as_view(),
        name="meal-vendor-gateway-punches",
    ),
    path(
        "entitlements/",
        MealEntitlementListCreateAPIView.as_view(),
        name="meal-entitlements",
    ),
    path(
        "rules/",
        MealEntitlementRuleListCreateAPIView.as_view(),
        name="meal-entitlement-rules",
    ),
    path(
        "rules/<int:pk>/",
        MealEntitlementRuleDetailAPIView.as_view(),
        name="meal-entitlement-rule-detail",
    ),
    path(
        "review-reminders/",
        MealReviewRemindersAPIView.as_view(),
        name="meal-review-reminders",
    ),
    path(
        "rates/",
        MealTicketRateListCreateAPIView.as_view(),
        name="meal-rates",
    ),
    path(
        "devices/",
        MealDeviceListAPIView.as_view(),
        name="meal-devices",
    ),
    path(
        "operations/",
        MealOperationsAPIView.as_view(),
        name="meal-operations",
    ),
    path(
        "employees/<int:pk>/profile/",
        EmployeeMealsProfileAPIView.as_view(),
        name="employee-meals-profile",
    ),
    path(
        "excess/<int:pk>/approve/",
        MealExcessApproveAPIView.as_view(),
        name="meal-excess-approve",
    ),
    path(
        "collections/<int:pk>/void/",
        MealCollectionVoidAPIView.as_view(),
        name="meal-collection-void",
    ),
    path(
        "excess/<int:pk>/decline/",
        MealExcessDeclineAPIView.as_view(),
        name="meal-excess-decline",
    ),
    path(
        "excess/<int:pk>/cancel/",
        MealExcessCancelAPIView.as_view(),
        name="meal-excess-cancel",
    ),
    path(
        "excess/bulk-decision/",
        MealExcessBulkDecisionAPIView.as_view(),
        name="meal-excess-bulk-decision",
    ),
    path(
        "excess/pending-ids/",
        MealExcessPendingIdsAPIView.as_view(),
        name="meal-excess-pending-ids",
    ),
    path("extra-authorizations/", MealExtraAuthorizationListCreateAPIView.as_view(), name="meal-extra-authorizations"),
    path("extra-authorizations/<int:pk>/cancel/", MealExtraAuthorizationCancelAPIView.as_view(), name="meal-extra-authorization-cancel"),
    path(
        "vendor/summary/",
        MealVendorSummaryAPIView.as_view(),
        name="meal-vendor-summary",
    ),
    path("vendor/multiple-tickets/", MealMultipleTicketsAPIView.as_view(), name="meal-multiple-tickets"),
    path("shift-report/", MealShiftReportAPIView.as_view(), name="meal-shift-report"),
    path("shift-report/decide/", MealShiftReportDecideAPIView.as_view(), name="meal-shift-report-decide"),
    path("chargebacks/", MealChargebackListCreateAPIView.as_view(), name="meal-chargebacks"),
    path("chargebacks/lookup/", MealChargebackLookupAPIView.as_view(), name="meal-chargeback-lookup"),
    path("chargebacks/<int:pk>/cancel/", MealChargebackCancelAPIView.as_view(), name="meal-chargeback-cancel"),
    path("vendor/claims/", MealVendorClaimCreateAPIView.as_view(), name="meal-vendor-claims"),
    path("vendor/claims/<int:pk>/", MealVendorClaimDetailAPIView.as_view(), name="meal-vendor-claim-detail"),
    path(
        "vendor/payments/",
        MealVendorPaymentListCreateAPIView.as_view(),
        name="meal-vendor-payments",
    ),
    path(
        "vendor/<int:payroll_period_id>/",
        MealVendorPeriodAPIView.as_view(),
        name="meal-vendor-period",
    ),
]
