from django.urls import path

from .bridge import MealVendorGatewayPunchBridgeAPIView
from .views import (
    EmployeeMealsProfileAPIView,
    MealDeviceListAPIView,
    MealEntitlementListCreateAPIView,
    MealEntitlementRuleDetailAPIView,
    MealEntitlementRuleListCreateAPIView,
    MealExcessApproveAPIView,
    MealCollectionVoidAPIView,
    MealExcessCancelAPIView,
    MealExcessDeclineAPIView,
    MealOperationsAPIView,
    MealReviewRemindersAPIView,
    MealTicketRateListCreateAPIView,
    MealVendorPaymentListCreateAPIView,
    MealVendorPeriodAPIView,
)

urlpatterns = [
    path(
        "integrations/vendor-gateway/punches/",
        MealVendorGatewayPunchBridgeAPIView.as_view(),
        name="meal-vendor-gateway-punches",
    ),
    path(
        "entitlements/",
        MealEntitlementListCreateAPIView.as_view(),
        name="meal-entitlements",
    ),
    path(
        "rules/",
        MealEntitlementRuleListCreateAPIView.as_view(),
        name="meal-entitlement-rules",
    ),
    path(
        "rules/<int:pk>/",
        MealEntitlementRuleDetailAPIView.as_view(),
        name="meal-entitlement-rule-detail",
    ),
    path(
        "review-reminders/",
        MealReviewRemindersAPIView.as_view(),
        name="meal-review-reminders",
    ),
    path(
        "rates/",
        MealTicketRateListCreateAPIView.as_view(),
        name="meal-rates",
    ),
    path(
        "devices/",
        MealDeviceListAPIView.as_view(),
        name="meal-devices",
    ),
    path(
        "operations/",
        MealOperationsAPIView.as_view(),
        name="meal-operations",
    ),
    path(
        "employees/<int:pk>/profile/",
        EmployeeMealsProfileAPIView.as_view(),
        name="employee-meals-profile",
    ),
    path(
        "excess/<int:pk>/approve/",
        MealExcessApproveAPIView.as_view(),
        name="meal-excess-approve",
    ),
    path(
        "collections/<int:pk>/void/",
        MealCollectionVoidAPIView.as_view(),
        name="meal-collection-void",
    ),
    path(
        "excess/<int:pk>/decline/",
        MealExcessDeclineAPIView.as_view(),
        name="meal-excess-decline",
    ),
    path(
        "excess/<int:pk>/cancel/",
        MealExcessCancelAPIView.as_view(),
        name="meal-excess-cancel",
    ),
    path(
        "vendor/payments/",
        MealVendorPaymentListCreateAPIView.as_view(),
        name="meal-vendor-payments",
    ),
    path(
        "vendor/<int:payroll_period_id>/",
        MealVendorPeriodAPIView.as_view(),
        name="meal-vendor-period",
    ),
]
