"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";

import { LeaveShell } from "@/components/leave/LeaveShell";
import type { LeaveRequest, ListResponse } from "@/components/leave/types";
import { PageHeader, Section, StatusBadge } from "@/components/ui";
import { apiFetch, getAccessToken } from "@/lib/api";
import { ErrorPanel, TableSkeleton } from "../requests/page";

export default function LeaveCalendarPage() {
  const router = useRouter(); const [requests, setRequests] = useState<LeaveRequest[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [month, setMonth] = useState(() => new Date(new Date().getFullYear(), new Date().getMonth(), 1)); const [department, setDepartment] = useState("");
  useEffect(() => { if (!getAccessToken()) { router.push("/login"); return; } void loadRequests(); }, [router]);
  async function loadRequests() { setLoading(true); setError(""); try { const response = await apiFetch("/leave/requests/"); if (!response.ok) throw new Error("Unable to load leave calendar."); const data: ListResponse<LeaveRequest> = await response.json(); setRequests(data.results); } catch (loadError) { setError(loadError instanceof Error ? loadError.message : "Unable to load leave calendar."); } finally { setLoading(false); } }
  const departments = Array.from(new Set(requests.map((request) => request.department_name).filter((value): value is string => Boolean(value)))).sort();
  const visibleRequests = requests.filter((request) => (!department || request.department_name === department) && overlapsMonth(request, month));
  const days = monthDays(month);
  return <LeaveShell><PageHeader title="Leave Calendar" description="A monthly view of submitted leave requests." actions={<div className="flex gap-2"><button onClick={() => setMonth(new Date(month.getFullYear(), month.getMonth() - 1, 1))} className="rounded-xl border border-slate-300 bg-white px-3 py-2 text-sm">Previous</button><button onClick={() => setMonth(new Date(month.getFullYear(), month.getMonth() + 1, 1))} className="rounded-xl border border-slate-300 bg-white px-3 py-2 text-sm">Next</button></div>} />{error ? <ErrorPanel message={error} retry={loadRequests} /> : <Section title={month.toLocaleDateString("en-GB", { month: "long", year: "numeric" })} actions={<select value={department} onChange={(event) => setDepartment(event.target.value)} className="rounded-xl border border-slate-300 bg-white px-3 py-2 text-sm"><option value="">All departments</option>{departments.map((item) => <option key={item} value={item}>{item}</option>)}</select>}>{loading ? <TableSkeleton /> : <><div className="grid grid-cols-7 border-b border-slate-200 bg-slate-50 text-center text-xs font-semibold uppercase tracking-wide text-slate-500">{["Mon","Tue","Wed","Thu","Fri","Sat","Sun"].map((day) => <div key={day} className="p-3">{day}</div>)}</div><div className="grid grid-cols-7">{days.map((day, index) => <div key={`${day?.toISOString()}-${index}`} className="min-h-28 border-b border-r border-slate-100 p-2 last:border-r-0">{day && <><p className="text-sm font-semibold text-slate-700">{day.getDate()}</p>{visibleRequests.filter((request) => coversDay(request, day)).slice(0, 2).map((request) => <div key={request.id} title={`${request.employee_name}: ${request.leave_type_name}`} className={`mt-1 truncate rounded px-2 py-1 text-xs font-medium ${request.status === "approved" ? "bg-emerald-100 text-emerald-800" : "bg-amber-100 text-amber-800"}`}>{request.employee_name}</div>)}</>}</div>)}</div><div className="divide-y divide-slate-100 p-5 md:hidden">{visibleRequests.map((request) => <div key={request.id} className="py-3"><p className="font-semibold">{request.employee_name}</p><p className="text-sm text-slate-500">{request.leave_type_name}: {request.start_date} to {request.end_date}</p><StatusBadge status={request.status} /></div>)}</div></>}</Section>}</LeaveShell>;
}
function overlapsMonth(request: LeaveRequest, month: Date) { const start = new Date(`${request.start_date}T00:00:00`); const end = new Date(`${request.end_date}T00:00:00`); const last = new Date(month.getFullYear(), month.getMonth() + 1, 0); return start <= last && end >= month; }
function coversDay(request: LeaveRequest, day: Date) { const start = new Date(`${request.start_date}T00:00:00`); const end = new Date(`${request.end_date}T23:59:59`); return start <= day && end >= day; }
function monthDays(month: Date) { const first = new Date(month.getFullYear(), month.getMonth(), 1); const last = new Date(month.getFullYear(), month.getMonth() + 1, 0); const slots: Array<Date | null> = Array((first.getDay() + 6) % 7).fill(null); for (let day = 1; day <= last.getDate(); day += 1) slots.push(new Date(month.getFullYear(), month.getMonth(), day)); while (slots.length % 7) slots.push(null); return slots; }
