# Generated by Django 6.1 on 2026-09-03 17:43

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0006_alter_biometricidentity_system'),
        ('payroll', '0003_payrolllineitem_unique_system_payroll_line_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PPEType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('description', models.TextField(blank=True)),
                ('potentially_employee_deductible', models.BooleanField(default=False)),
                ('default_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeePPEIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('issue_date', models.DateField()),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_cost', models.DecimalField(decimal_places=2, editable=False, max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('employee_deductible', models.BooleanField(default=False)),
                ('deduction_status', models.CharField(choices=[('not_deductible', 'Not deductible'), ('pending', 'Pending HR review'), ('approved', 'Approved'), ('held', 'Held'), ('deferred', 'Deferred'), ('deducted', 'Deducted')], default='not_deductible', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deducted_payroll', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ppe_deduction_issues', to='payroll.employeepayroll')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ppe_issues', to='employees.employee')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ppe_issues_recorded', to=settings.AUTH_USER_MODEL)),
                ('payroll_line_item', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ppe_issue', to='payroll.payrolllineitem')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ppe_issues_reviewed', to=settings.AUTH_USER_MODEL)),
                ('target_payroll_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ppe_deduction_issues', to='payroll.payrollperiod')),
                ('ppe_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='ppe.ppetype')),
            ],
            options={
                'ordering': ['-issue_date', '-id'],
                'permissions': [('record_ppe_issue', 'Can record PPE issues'), ('review_ppe_deduction', 'Can review PPE deductions')],
            },
        ),
    ]
