# Generated by Django 6.1 on 2026-09-19 10:41

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0010_alter_employee_options_employee_account_number_and_more'),
        ('payroll', '0004_approve_employee_payrolls_of_approved_periods'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeferredFundAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('active', models.BooleanField(default=True)),
                ('enrolled_on', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='deferred_fund', to='employees.employee')),
            ],
            options={
                'ordering': ['employee__employee_id'],
                'permissions': [('view_deferred_funds', 'Can view deferred funds'), ('manage_deferred_funds', 'Can enrol staff, set percentages and record withdrawals'), ('approve_deferred_withdrawal', 'Can approve or decline deferred fund withdrawals'), ('pay_deferred_withdrawal', 'Can pay out deferred fund withdrawals')],
            },
        ),
        migrations.CreateModel(
            name='DeferredFundWithdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('partial', 'Partial withdrawal'), ('final', 'Full release (leaving with notice)')], default='partial', max_length=10)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('requested', 'Awaiting management approval'), ('approved', 'Approved - awaiting payment'), ('declined', 'Declined'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='requested', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_comment', models.TextField(blank=True)),
                ('paid_on', models.DateField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=120)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='withdrawals', to='deferredfunds.deferredfundaccount')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DeferredFundEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('contribution', 'Monthly contribution'), ('withdrawal', 'Withdrawal'), ('release', 'Full release on exit'), ('adjustment', 'Adjustment'), ('opening', 'Opening balance')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('entry_date', models.DateField()),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='deferredfunds.deferredfundaccount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('line_item', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deferred_fund_entry', to='payroll.payrolllineitem')),
                ('payroll_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deferred_fund_entries', to='payroll.payrollperiod')),
            ],
            options={
                'ordering': ['entry_date', 'id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('entry_type', 'contribution')), fields=('account', 'payroll_period'), name='one_contribution_per_period')],
            },
        ),
    ]
