# Generated by Django 6.1 on 2026-09-19 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deferredfunds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deferredfundaccount',
            name='saving_since',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deferredfundwithdrawal',
            name='leaving_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deferredfundwithdrawal',
            name='notice_given_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deferredfundwithdrawal',
            name='rule_exceptions',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='deferredfundentry',
            name='entry_type',
            field=models.CharField(choices=[('contribution', 'Monthly contribution'), ('withdrawal', 'Withdrawal'), ('release', 'Full release on exit'), ('forfeiture', 'Forfeited to the company'), ('adjustment', 'Adjustment'), ('opening', 'Opening balance')], max_length=20),
        ),
    ]
