# Generated by Django 6.1 on 2026-10-08 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deferredfunds', '0002_policy_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='deferredfundaccount',
            name='contributions_from',
            field=models.DateField(blank=True, null=True),
        ),
    ]
