# Generated by Django 6.1 on 2026-09-19 09:23

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0010_alter_employee_options_employee_account_number_and_more'),
        ('payroll', '0004_approve_employee_payrolls_of_approved_periods'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryAdvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('reason', models.TextField(blank=True)),
                ('repayment_months', models.PositiveSmallIntegerField(default=1)),
                ('deduct_from_year', models.PositiveSmallIntegerField()),
                ('deduct_from_month', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('requested', 'Awaiting management approval'), ('approved', 'Approved - awaiting payment'), ('declined', 'Declined'), ('paid', 'Paid - being repaid'), ('repaid', 'Fully repaid'), ('cancelled', 'Cancelled')], default='requested', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_comment', models.TextField(blank=True)),
                ('paid_on', models.DateField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=120)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advances_decided', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salary_advances', to='employees.employee')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advances_paid', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advances_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'permissions': [('record_salary_advance', 'Can record salary advance requests'), ('approve_salary_advance', 'Can approve or decline salary advances'), ('pay_salary_advance', 'Can pay out approved salary advances')],
            },
        ),
        migrations.CreateModel(
            name='AdvanceRepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('line_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='advance_repayment', to='payroll.payrolllineitem')),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advance_repayments', to='payroll.employeepayroll')),
                ('payroll_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advance_repayments', to='payroll.payrollperiod')),
                ('advance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='advances.salaryadvance')),
            ],
            options={
                'ordering': ['payroll_period__year', 'payroll_period__month', 'id'],
                'constraints': [models.UniqueConstraint(fields=('advance', 'payroll_period'), name='one_advance_repayment_per_period')],
            },
        ),
    ]
