# Generated by Django 6.1 on 2026-09-19 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0010_alter_employee_options_employee_account_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('kind', models.CharField(choices=[('company', 'Company accommodation'), ('external', 'Outside accommodation')], default='company', max_length=20)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['kind', 'sort_order', 'name'],
                'permissions': [('view_accommodation', 'Can view accommodation'), ('manage_accommodation', 'Can manage accommodation')],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('capacity', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('capacity_estimated', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='accommodation.building')),
            ],
            options={
                'ordering': ['building__sort_order', 'building__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RoomAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('assigned_on', models.DateField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='room_assignment', to='employees.employee')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='accommodation.room')),
            ],
            options={
                'ordering': ['room__name', 'bed_number', 'employee__employee_id'],
            },
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('building', 'name'), name='unique_room_per_building'),
        ),
        migrations.AddConstraint(
            model_name='roomassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('bed_number__isnull', False)), fields=('room', 'bed_number'), name='one_person_per_bed'),
        ),
    ]
