# Generated by Django 6.1 on 2026-10-02 12:39

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offences', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('reward_first', models.TextField(blank=True)),
                ('reward_second', models.TextField(blank=True)),
                ('amount_first', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('amount_second', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('auto_rule', models.CharField(blank=True, choices=[('', 'Recorded by hand'), ('no_absence', 'Proposed automatically: no absence in the month'), ('no_lateness', 'Proposed automatically: no lateness in the month')], default='', max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'category', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='offencetype',
            options={'ordering': ['sort_order', 'category', 'name']},
        ),
        migrations.AddField(
            model_name='employeeoffence',
            name='occurrence',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='employeeoffence',
            name='penalty_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='offencetype',
            name='amount_first',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='offencetype',
            name='amount_second',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='offencetype',
            name='amount_third',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='offencetype',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='offencetype',
            name='penalty_first',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='offencetype',
            name='penalty_second',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='offencetype',
            name='penalty_third',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='offencetype',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='employeeoffence',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='offencetype',
            name='default_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='offencetype',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AddConstraint(
            model_name='offencetype',
            constraint=models.UniqueConstraint(fields=('category', 'name'), name='unique_offence_type_per_category'),
        ),
        migrations.AddConstraint(
            model_name='rewardtype',
            constraint=models.UniqueConstraint(fields=('category', 'name'), name='unique_reward_type_per_category'),
        ),
    ]
