# Generated by Django 6.1 on 2026-09-06 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeedocument',
            options={'ordering': ['-uploaded_at'], 'permissions': [('view_documents', 'Can view employee documents'), ('manage_documents', 'Can upload and delete employee documents')]},
        ),
    ]
