# Generated by Django 6.1 on 2026-09-02 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payrollperiod',
            options={'ordering': ['-year', '-month'], 'permissions': [('view_payroll', 'Can view payroll'), ('manage_payroll', 'Can manage payroll periods and records')]},
        ),
    ]
