# Generated by Django 6.1 on 2026-09-03 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_alter_payrollperiod_options'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='payrolllineitem',
            constraint=models.UniqueConstraint(condition=models.Q(('is_system_generated', True)), fields=('payroll', 'source_type', 'source_reference'), name='unique_system_payroll_line_source'),
        ),
    ]
