# Generated by Django 6.1 on 2026-09-19 19:35

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0011_employee_gender'),
        ('payroll', '0004_approve_employee_payrolls_of_approved_periods'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('performance', 'Performance bonus'), ('employee_of_month', 'Employee of the Month'), ('other', 'Other bonus')], default='performance', max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('reason', models.TextField()),
                ('performance_year', models.PositiveSmallIntegerField()),
                ('performance_month', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('pay_year', models.PositiveSmallIntegerField()),
                ('pay_month', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('status', models.CharField(choices=[('proposed', 'Awaiting management approval'), ('approved', 'Approved - goes into payroll'), ('paid', 'In payroll'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], default='proposed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_comment', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bonuses', to='employees.employee')),
                ('payroll', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bonuses', to='payroll.employeepayroll')),
                ('payroll_line_item', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bonus', to='payroll.payrolllineitem')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-performance_year', '-performance_month', '-created_at'],
                'permissions': [('view_bonuses', 'Can view bonuses and employees of the month'), ('record_bonus', 'Can record bonuses and propose employees of the month'), ('approve_bonus', 'Can approve or decline bonuses and employees of the month')],
            },
        ),
        migrations.CreateModel(
            name='EmployeeOfTheMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('reason', models.TextField()),
                ('reward_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('status', models.CharField(choices=[('proposed', 'Awaiting management approval'), ('approved', 'Approved'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], default='proposed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_comment', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bonus', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_of_the_month', to='bonuses.bonus')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees_of_the_month', to='employees.department')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_of_the_month_awards', to='employees.employee')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-month', 'department__name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['proposed', 'approved'])), fields=('department', 'year', 'month'), name='one_employee_of_the_month_per_department')],
            },
        ),
    ]
