# Generated by Django 6.1 on 2026-10-02 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonuses', '0001_initial'),
        ('employees', '0011_employee_gender'),
        ('offences', '0002_rewardtype_alter_offencetype_options_and_more'),
        ('payroll', '0005_employeepayroll_bank_details_snapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bonus',
            name='occurrence',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bonus',
            name='reward_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bonuses', to='offences.rewardtype'),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='kind',
            field=models.CharField(choices=[('performance', 'Performance bonus'), ('employee_of_month', 'Employee of the Month'), ('policy_reward', 'Policy reward'), ('other', 'Other bonus')], default='performance', max_length=30),
        ),
        migrations.AddConstraint(
            model_name='bonus',
            constraint=models.UniqueConstraint(condition=models.Q(('reward_type__isnull', False), ('status__in', ['proposed', 'approved', 'paid'])), fields=('employee', 'reward_type', 'performance_year', 'performance_month'), name='one_policy_reward_per_person_per_month'),
        ),
    ]
