# Generated by Django 6.1 on 2026-09-02 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_seed_standard_shifts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendanceexception',
            options={'permissions': [('review_attendanceexception', 'Can review attendance exceptions')]},
        ),
    ]
