# Generated by Django 6.1 on 2026-09-02 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_attendanceexception_options'),
        ('employees', '0005_employee_employment_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeRosterDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('work', 'Work'), ('rest', 'Rest')], max_length=12)),
                ('source', models.CharField(choices=[('generated', 'Generated'), ('manual', 'Manual'), ('override', 'Manual override')], default='manual', max_length=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_roster_days', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster_days', to='employees.employee')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='roster_days', to='attendance.shift')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_roster_days', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date', 'employee__last_name', 'employee__first_name'],
                'permissions': [('manage_roster', 'Can manage employee work rosters')],
                'constraints': [models.UniqueConstraint(fields=('employee', 'date'), name='unique_employee_roster_day')],
            },
        ),
    ]
