# Generated by Django 6.1 on 2026-09-02 19:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_employeerosterday'),
        ('employees', '0005_employee_employment_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='employeerosterday',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('shift__isnull', False), ('status', 'work')), models.Q(('shift__isnull', True), ('status', 'rest')), _connector='OR'), name='roster_day_status_matches_shift'),
        ),
    ]
