# Generated by Django 6.1 on 2026-09-03 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_employeerosterday_roster_day_status_matches_shift'),
        ('employees', '0005_employee_employment_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OvertimeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField()),
                ('scheduled_end', models.DateTimeField()),
                ('actual_clock_out', models.DateTimeField()),
                ('threshold_minutes_snapshot', models.PositiveIntegerField()),
                ('potential_overtime_minutes', models.PositiveIntegerField()),
                ('approved_overtime_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=12)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_comment', models.TextField(blank=True)),
                ('basic_salary_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('roster_work_days_snapshot', models.PositiveIntegerField(blank=True, null=True)),
                ('daily_rate_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('scheduled_shift_minutes_snapshot', models.PositiveIntegerField(blank=True, null=True)),
                ('normal_hourly_rate_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('overtime_multiplier_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('overtime_hourly_rate_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('payable_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('payment_due_date', models.DateField()),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=12)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payment_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendance', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='overtime_record', to='attendance.dailyattendance')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='overtime_records', to='employees.employee')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_overtime_records', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_overtime_records', to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='overtime_records', to='attendance.shift')),
            ],
            options={
                'ordering': ['-work_date', 'employee__last_name', 'employee__first_name'],
                'permissions': [('review_overtime', 'Can review overtime records')],
            },
        ),
    ]
