# Generated by Django 6.1 on 2026-09-03 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_overtimerecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceexception',
            name='exception_type',
            field=models.CharField(choices=[('late', 'Late Arrival'), ('early_departure', 'Early Departure'), ('absence', 'Absence'), ('missing_clock_in', 'Missing Clock In'), ('missing_clock_out', 'Missing Clock Out'), ('hostel_violation', 'Hostel During Shift'), ('leave_punch_conflict', 'Punch while on approved leave')], max_length=30),
        ),
    ]
