# Generated by Django 6.1 on 2026-09-06 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_alter_attendanceexception_exception_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shiftassignment',
            options={'permissions': [('manage_shifts', 'Can assign and change employee shifts')]},
        ),
    ]
