# Generated by Django 6.1 on 2026-09-16 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_alter_shiftassignment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biometricdevice',
            options={'permissions': [('manage_devices', 'Can register and manage biometric devices')]},
        ),
        migrations.AddField(
            model_name='biometricdevice',
            name='purpose',
            field=models.CharField(choices=[('attendance', 'Attendance'), ('meal_ticket', 'Meal Ticket')], default='attendance', max_length=20),
        ),
    ]
