# Generated by Django 6.1 on 2026-09-18 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_devicecommand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicecommand',
            name='command_type',
            field=models.CharField(choices=[('enroll_user', 'Enroll User'), ('delete_user', 'Delete User'), ('refresh_enrolled_ids', 'Refresh Enrolled IDs'), ('clone_enrollment', 'Clone Enrollment To Other Devices')], max_length=30),
        ),
    ]
