# Generated by Django 6.1 on 2026-09-21 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0012_alter_devicecommand_command_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicecommand',
            name='command_type',
            field=models.CharField(choices=[('enroll_user', 'Enroll User'), ('delete_user', 'Delete User'), ('refresh_enrolled_ids', 'Refresh Enrolled IDs'), ('clone_enrollment', 'Clone Enrollment To Other Devices'), ('purge_user', 'Remove Inactive User From Device'), ('set_user_enabled', 'Enable Or Disable User On Terminal')], max_length=30),
        ),
    ]
