# Generated by Django 6.1 on 2026-09-21 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0013_alter_devicecommand_command_type'),
        ('employees', '0011_employee_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('kind', models.CharField(choices=[('fixed', 'Fixed shift'), ('rotation', 'Weekly Day / Night rotation')], max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('working_weekdays', models.JSONField(blank=True, default=list)),
                ('anchor_monday', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('day_shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='attendance.shift')),
                ('night_shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='attendance.shift')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='attendance.shift')),
            ],
        ),
        migrations.CreateModel(
            name='ShiftPlanAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(blank=True, max_length=1)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('assigned_by', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_plan_assignments', to='employees.employee')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='attendance.shiftplan')),
            ],
            options={
                'ordering': ['-start_date', '-id'],
            },
        ),
    ]
