# Generated by Django 6.1 on 2026-10-02 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0015_list_user_slots_command'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biometricdevice',
            options={'permissions': [('manage_devices', 'Can register and manage biometric devices'), ('view_biometrics_overview', 'Can view who is and is not enrolled on biometric devices')]},
        ),
    ]
