# Generated by Django 6.1 on 2026-10-02 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0016_alter_biometricdevice_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftplan',
            name='kind',
            field=models.CharField(choices=[('fixed', 'Fixed shift'), ('rotation', 'Weekly Day / Night rotation'), ('alternating', 'Weekly alternating shifts')], max_length=20),
        ),
    ]
