# Generated by Django 6.1 on 2026-10-02 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0017_alter_shiftplan_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftplan',
            name='saturday_shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='attendance.shift'),
        ),
    ]
