# Generated by Django 6.1 on 2026-10-02 17:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0018_shiftplan_saturday_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftplanassignment',
            name='day_off',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(6)]),
        ),
    ]
