# Generated by Django 6.1 on 2026-10-03 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0019_shiftplanassignment_day_off'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='is_flexible',
            field=models.BooleanField(default=False),
        ),
    ]
