# Generated by Django 6.1 on 2026-10-08 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0022_grant_enroll_to_device_managers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendanceexception',
            options={'permissions': [('review_attendanceexception', 'Can review attendance exceptions'), ('reverse_attendance_charge', 'Can reverse or change an attendance charge after it was decided')]},
        ),
    ]
